version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: insider
      POSTGRES_PASSWORD: insider
      POSTGRES_DB: insider_league
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
